---
- name: Check if rich rule for {{ item.source_address }} and port {{ item.dest_port }} is already created in csf.allow
  ansible.builtin.shell: grep -e ^"{{ item.protocol }}|in|d={{ item.dest_port }}|s={{ item.source_address }}" /etc/csf/csf.allow
  register: rich_rule
  changed_when: false
  ignore_errors: true

- name: Add rich rule for {{ item.source_address }} and port {{ item.dest_port }} to csf.allow
  ansible.builtin.lineinfile:
    path: /etc/csf/csf.allow
    backrefs: false
    state: present
    backup: false
    line: "{{ item.protocol }}|in|d={{ item.dest_port }}|s={{ item.source_address }} #{{ item.comment }}"
  when: rich_rule.rc !=0
  # notify: reload csf
