---
- name: Check if port {{ item }} is already allowed in CSF TCP_IN
  ansible.builtin.shell: grep -e ^TCP_IN /etc/csf/csf.conf | grep "{{ item }}"
  register: port_allowed
  changed_when: false
  ignore_errors: true

- name: Add port {{ item }} to CSF TCP_IN
  ansible.builtin.lineinfile:
    path: /etc/csf/csf.conf
    backrefs: true
    state: present
    regexp: '^TCP_IN = "(.*)"'
    backup: false
    line: 'TCP_IN = "\1,{{ item }}"'
  when: port_allowed.rc !=0
