---
- name: Check if port {{ item }} is already allowed in CSF UDP_IN
  ansible.builtin.shell: grep -e ^UDP_IN /etc/csf/csf.conf | grep "{{ item }}"
  register: port_allowed
  changed_when: false
  ignore_errors: true

- name: Add port {{ item }} to CSF UDP_IN
  ansible.builtin.lineinfile:
    path: /etc/csf/csf.conf
    backrefs: true
    state: present
    regexp: '^UDP_IN = "(.*)"'
    backup: false
    line: 'UDP_IN = "\1,{{ item }}"'
  when: port_allowed.rc !=0
