---
- name: Check if CSF is installed
  stat:
    path: /usr/sbin/csf
  register: csf_installed

- name: Include CSF Tasks
  include_tasks: csf/main.yml
  when: csf_installed.stat.exists == true and ansible_os_family == 'RedHat'

- name: Include Firewalld Tasks
  include_tasks: firewalld/main.yml
  when: csf_installed.stat.exists == false and ansible_os_family == 'RedHat'

- name: Include Debian Tasks
  include_tasks: ufw/main.yml
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'